export const GET_IMAGES= 'GET_IMAGES';
export const DELETE_IMAGES= 'DELETE_IMAGES';
export const SEARCH_IMAGE_START= 'SEARCH_IMAGE_START';
export const GET_IMAGES_SUCCESS= 'GET_IMAGES_SUCCESS';
export const GET_IMAGES_FAILURE= 'GET_IMAGES_FAILURE';
